//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoxelRendererQuery.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoxelRendererQuery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die struct OctreeEntry
        ///{
        ///    int childrenStartIndex;
        ///    int hasData;
        ///};
        ///
        ///
        ///
        ///globallycoherent RWTexture3D&lt;int&gt; voxelDataBuffer;
        ///globallycoherent RWStructuredBuffer&lt;OctreeEntry&gt; accelerationStructureBuffer;
        ///
        ///int volumeInitialSize;
        ///int maxDepth; // is equivalent to maxIterations
        ///
        ///inline int getData(uint3 pixel)
        ///{
        ///    return voxelDataBuffer[pixel];
        ///}
        ///
        ///uint calculateRelativeIndex(uint v, uint d)
        ///{
        ///    return (uint) (v / (volumeInitialSize &gt;&gt; d));
        ///}
        ///
        ///uint calculateOctant(uint3 pos, uint d)
        ///{        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string axlr {
            get {
                return ResourceManager.GetString("axlr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #define MAX_ITERATION 256
        ///uniform int volumeInitialSize;
        ///
        ///uniform RWTexture2D&lt;float4&gt; backBuffer;
        ///
        ///
        ///globallycoherent RWTexture3D&lt;int&gt; voxelDataBuffer;
        ///int getData(int3 position)
        ///{
        ///    return voxelDataBuffer[position];
        ///}
        ///
        ///uniform float4x4 srMatrix;
        ///uniform float4x4 translationMatrix;
        ///struct Ray
        ///{
        ///    float3 origin;
        ///    float3 dir;
        ///    float3 dirRcp;
        ///    
        ///};
        ///
        ///struct AABB
        ///{
        ///    float3 center;
        ///    float3 maxSize;
        ///};
        ///AABB createAABB(float3 center, float3 max)
        ///{
        ///    AABB aabb = (AABB) [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string raytracer {
            get {
                return ResourceManager.GetString("raytracer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $$$RTRCRESULT$$$ $$$VOLUME_RAYTEST$$$(Ray ray)
        ///{
        ///	ray.origin = mul(float4(ray.origin, 1), mul(translationMatrix, srMatrix)); 
        ///                   ray.dir = mul(float4(ray.dir, 0), srMatrix);
        ///                   ray.dirRcp = rcp(ray.dir);
        ///
        ///	float depth = 0;
        ///    float3 hitPoint = (float3) 0;
        ///    float3 hitPointInt = (float3) 0;
        ///    float3 normal = (float3) 0;
        ///    AABB voxelAABB = (AABB) 0;
        ///    AABB voxelAABBLast = (AABB) 0;
        ///    int voxelData = 0;
        ///    int iterations = 0;
        ///	bool result = false;
        ///	
        ///	 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string volumeRayTest {
            get {
                return ResourceManager.GetString("volumeRayTest", resourceCulture);
            }
        }
    }
}
